apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redundancies.custom.controller
spec:
  group: custom.controller
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer # default: 1
                redundancy:
                  type: integer # default: replicas/2
                template:
                  type: object
                  properties:
                    spec:
                      type: object
                      properties:
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              image:
                                type: string
                              ports:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    containerPort:
                                      type: integer
            status:
                type: object
                properties:
                  availableReplicas:
                    type: integer
                  currentReplicas:
                    type: integer
                  desiredReplicas:
                    type: integer
                  readyReplicas:
                    type: integer
                  replicas:
                    type: integer
                  updatedReplicas:
                    type: integer
                  redundancy:
                    type: integer
                  template:
                    type: object
                    properties:
                      spec:
                        type: object
                        properties:
                          containers:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                image:
                                  type: string
                                ports:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      containerPort:
                                        type: integer
  names:
    kind: Redundancy
    plural: redundancies
    singular: redundancy
  scope: Namespaced
