/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	v1 "custom-controller/pkg/apis/customcontroller/v1"
	scheme "custom-controller/pkg/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RedundanciesGetter has a method to return a RedundancyInterface.
// A group's client should implement this interface.
type RedundanciesGetter interface {
	Redundancies(namespace string) RedundancyInterface
}

// RedundancyInterface has methods to work with Redundancy resources.
type RedundancyInterface interface {
	Create(ctx context.Context, redundancy *v1.Redundancy, opts metav1.CreateOptions) (*v1.Redundancy, error)
	Update(ctx context.Context, redundancy *v1.Redundancy, opts metav1.UpdateOptions) (*v1.Redundancy, error)
	UpdateStatus(ctx context.Context, redundancy *v1.Redundancy, opts metav1.UpdateOptions) (*v1.Redundancy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Redundancy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.RedundancyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Redundancy, err error)
	RedundancyExpansion
}

// redundancies implements RedundancyInterface
type redundancies struct {
	client rest.Interface
	ns     string
}

// newRedundancies returns a Redundancies
func newRedundancies(c *RedundancyV1Client, namespace string) *redundancies {
	return &redundancies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the redundancy, and returns the corresponding redundancy object, and an error if there is any.
func (c *redundancies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Redundancy, err error) {
	result = &v1.Redundancy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("redundancies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Redundancies that match those selectors.
func (c *redundancies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RedundancyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.RedundancyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("redundancies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested redundancies.
func (c *redundancies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("redundancies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a redundancy and creates it.  Returns the server's representation of the redundancy, and an error, if there is any.
func (c *redundancies) Create(ctx context.Context, redundancy *v1.Redundancy, opts metav1.CreateOptions) (result *v1.Redundancy, err error) {
	result = &v1.Redundancy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("redundancies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(redundancy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a redundancy and updates it. Returns the server's representation of the redundancy, and an error, if there is any.
func (c *redundancies) Update(ctx context.Context, redundancy *v1.Redundancy, opts metav1.UpdateOptions) (result *v1.Redundancy, err error) {
	result = &v1.Redundancy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("redundancies").
		Name(redundancy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(redundancy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *redundancies) UpdateStatus(ctx context.Context, redundancy *v1.Redundancy, opts metav1.UpdateOptions) (result *v1.Redundancy, err error) {
	result = &v1.Redundancy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("redundancies").
		Name(redundancy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(redundancy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the redundancy and deletes it. Returns an error if one occurs.
func (c *redundancies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("redundancies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *redundancies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("redundancies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched redundancy.
func (c *redundancies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Redundancy, err error) {
	result = &v1.Redundancy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("redundancies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
