/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	customcontrollerv1 "custom-controller/pkg/apis/customcontroller/v1"
	versioned "custom-controller/pkg/clientset/versioned"
	internalinterfaces "custom-controller/pkg/informers/externalversions/internalinterfaces"
	v1 "custom-controller/pkg/listers/customcontroller/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RedundancyInformer provides access to a shared informer and lister for
// Redundancies.
type RedundancyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.RedundancyLister
}

type redundancyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRedundancyInformer constructs a new informer for Redundancy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRedundancyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRedundancyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRedundancyInformer constructs a new informer for Redundancy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRedundancyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RedundancyV1().Redundancies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RedundancyV1().Redundancies(namespace).Watch(context.TODO(), options)
			},
		},
		&customcontrollerv1.Redundancy{},
		resyncPeriod,
		indexers,
	)
}

func (f *redundancyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRedundancyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *redundancyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&customcontrollerv1.Redundancy{}, f.defaultInformer)
}

func (f *redundancyInformer) Lister() v1.RedundancyLister {
	return v1.NewRedundancyLister(f.Informer().GetIndexer())
}
